services:
  - type: web
    name: trust-assistant-backend
    env: node
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://trustmecro.netlify.app
      - key: JWT_EXPIRY
        value: 7d
    plan: free
    region: oregon
    autoDeploy: true
    build:
      nodeVersion: 18.x
